# Generated by Django 3.1.4 on 2021-07-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('groceries', 'groceries'), ('milk products', 'milk products'), ('clay vessels', 'clay vessels'), ('ayurvedic herbs and herbal juices', 'ayurvedic herbs and herbal juices'), ('gluten free products', 'gluten free products'), ('ready to eat', 'ready to eat'), ('beverages', 'beverages'), ('personal care products', 'personal care products'), ('organic Teas', 'organic Teas'), ('miscellaneous', 'miscellaneous'), ('natural air purifiers', 'natural air purifiers'), ('vegetable and fruits', 'vegetable and fruits')], max_length=100)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
    ]
