# Generated by Django 3.1.4 on 2021-07-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='User',
            new_name='user',
        ),
    ]
