# Generated by Django 3.2.5 on 2021-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
