# Generated by Django 3.2.5 on 2021-08-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210828_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
