# Generated by Django 3.2.5 on 2021-08-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_product_discounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
