# Generated by Django 3.2.5 on 2021-08-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_orderplaced_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discounted',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
