# Generated by Django 3.2.5 on 2021-08-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_cart_discounted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discounted',
        ),
    ]
