# Generated by Django 3.2.5 on 2021-09-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_product_is_instock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAwareness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100000)),
                ('image', models.ImageField(upload_to='awarenessImage')),
                ('video', models.CharField(max_length=10000)),
            ],
        ),
    ]
