# Generated by Django 3.2.5 on 2021-09-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_dailyawareness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('organic groceries', 'organic groceries'), ('dairy products', 'dairy products'), ('cooking vessels', 'cooking vessels'), ('ayurvedic herbs and herbal juices', 'ayurvedic herbs and herbal juices'), ('poojan samagri', 'poojan samagri'), ('ready to eat', 'ready to eat'), ('beverages', 'beverages'), ('personal care products', 'personal care products'), ('sweets and snacks', 'sweets and snacks'), ('miscellaneous', 'miscellaneous'), ('natural air purifiers', 'natural air purifiers'), ('vegetable and fruits', 'vegetable and fruits'), ('Breakfast Cereals', 'Breakfast Cereals'), ('Oils & Ghee', 'Oils & Ghee'), ('Dry Fruits', 'Dry Fruits'), ('flour', 'flour'), ('rice', 'rice'), ('pulses', 'pulses'), ('millets', 'millets'), ('spices', 'spices'), ('honey/sugar/sweetner', 'honey/sugar/sweetner'), ('tea', 'tea')], max_length=100),
        ),
    ]
