# Generated by Django 3.2.9 on 2022-03-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_cart_discounted copy'),
        ('myapp', '0020_productimage'),
    ]

    operations = [
    ]
