# Generated by Django 3.2.9 on 2022-03-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_merge_0012_cart_discounted copy_0020_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discounted',
        ),
        migrations.AlterField(
            model_name='dailyawareness',
            name='text',
            field=models.TextField(max_length=16382),
        ),
        migrations.AlterField(
            model_name='dailyawareness',
            name='video',
            field=models.CharField(max_length=1000),
        ),
    ]
